stats/urls.py
from django.urls import path
from .views import StatsList, aggregation, upload, match_list, match_details, aggregation


urlpatterns = [
    path('', StatsList.as_view(), name='home'),
    path('aggregation', aggregation, name='aggregation'),
    path('upload', upload, name='upload'),
    path('matches', match_list, name='matches'),
    path('matches/<int:pk>', match_details, name='match'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stats.urls')),
    path('', include('django.contrib.auth.urls')),
]

stats/models.py
from django.db import models
from django.urls import reverse


class Upload(models.Model):
    file = models.FileField(upload_to='uploads')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['-date']

    def get_absolute_url(self):
        return reverse('home')


class Match(models.Model):
    date = models.DateTimeField()

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['-date']

    def get_absolute_url(self):
        return reverse('home')


class StatLine(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    date = models.DateTimeField()
    player = models.CharField(max_length=255)
    min = models.FloatField()
    made_2 = models.IntegerField()
    attempts_2 = models.IntegerField()
    made_3 = models.IntegerField()
    attempts_3 = models.IntegerField()
    made_ft = models.IntegerField()
    attempts_ft = models.IntegerField()
    reb_o = models.IntegerField()
    reb_d = models.IntegerField()
    assist = models.IntegerField()
    poa = models.IntegerField()
    pf = models.IntegerField()
    fd = models.IntegerField()
    steals = models.IntegerField()
    turnovers = models.IntegerField()
    blocks = models.IntegerField()

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.player

    @property
    def percentage_2(self):
        if self.attempts_2 == 0:
            return 0.0
        x = float(self.made_2/self.attempts_2)
        return (round(x, 2))

    @property
    def percentage_3(self):
        if self.attempts_3 == 0:
            return 0.0
        x = float(self.made_3/self.attempts_3)
        return (round(x, 2))

    @property
    def percentage_ft(self):
        if self.attempts_ft == 0:
            return 0.0
        x = float(self.made_ft/self.attempts_ft)
        return (round(x, 2))

    @property
    def reb_t(self):
        x = int(self.reb_o) + int(self.reb_d)
        return x

    # @property
    #   def pts(self):

stats/forms.py
from django import forms
from .models import Upload


class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ('file', )
        widgets = {
            'file': forms.FileInput(attrs={'class': 'form-control'}),
        }

stats/views.py
from datetime import datetime

import pandas
import pytz
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView
from django.db.models import Sum

from .forms import UploadForm
from .models import Match, StatLine


def login(request):
    if request.method == 'POST':
        return redirect('home')
    return render(request, 'login.html')


def aggregation(request):
    # from = request.args.forms
    # to = request.args.to
    queryset = StatLine.objects.all()
    players = []
    for stat in queryset:
        x = stat.player
        if x not in players:
            players.append(x)
    players_agg = []
    for x in players:
        agg_line = StatLine.objects.filter(player=x).aggregate(
            sum_min=Sum('min'),
            sum_made_2=Sum('made_2'),
            sum_attempts_2=Sum('attempts_2'),

            sum_made_3=Sum('made_3'),
            sum_attempts_3=Sum('attempts_3'),

            sum_made_ft=Sum('made_ft'),
            sum_attempts_ft=Sum('attempts_ft'),

            sum_reb_o=Sum('reb_o'),
            sum_reb_d=Sum('reb_d'),

            sum_assist=Sum('assist'),
            sum_poa=Sum('poa'),
            sum_pf=Sum('pf'),
            sum_fd=Sum('fd'),
            sum_steals=Sum('steals'),
            sum_turnovers=Sum('turnovers'),
            sum_blocks=Sum('blocks'),
        )

        agg_line['player'] = x
        agg_line['sum_min'] = round(agg_line['sum_min'], 2)

        agg_line['percentage_2'] = 0
        if agg_line['sum_attempts_2'] != 0 and agg_line['sum_made_2'] != 0:
            agg_line['percentage_2'] = agg_line['sum_made_2'] / \
                agg_line['sum_attempts_2']
            agg_line['percentage_2'] = round(agg_line['percentage_2'], 2)

        agg_line['percentage_3'] = 0
        if agg_line['sum_attempts_3'] != 0 and agg_line['sum_made_3'] != 0:
            agg_line['percentage_3'] = agg_line['sum_made_3'] / \
                agg_line['sum_attempts_3']
            agg_line['percentage_3'] = round(agg_line['percentage_3'], 2)

        agg_line['percentage_ft'] = 0
        if agg_line['sum_attempts_ft'] != 0 and agg_line['sum_made_ft'] != 0:
            agg_line['percentage_ft'] = agg_line['sum_made_ft'] / \
                agg_line['sum_attempts_ft']
            agg_line['percentage_ft'] = round(agg_line['percentage_ft'], 2)

        agg_line['sum_reb_t'] = agg_line['sum_reb_o'] + agg_line['sum_reb_d']

        players_agg.append(agg_line)

    return render(request, 'aggregation.html', {
        'players_agg': players_agg,
    }
    )


class StatsList(ListView):
    queryset = StatLine.objects.all()
    template_name = 'home.html'
    paginate_by = 50


def upload(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            xls = pandas.ExcelFile(request.FILES['file'])
            for sheet in xls.sheet_names:
                dataframe = pandas.read_excel(
                    xls, sheet_name=sheet, skiprows=2, header=None)
                dataframe = dataframe.reset_index()
                for row in dataframe.itertuples():
                    game_month, dates = sheet.split(' ')
                    date = dates.split('.')
                    game_time = 1
                    game_date = date[0]
                    if len(date) == 2:
                        game_time = date[1]
                    dt = datetime.strptime(
                        f"{game_month} {game_date} 2022 {game_time}", '%b %d %Y %I')
                    match_date = {
                        'date': dt,
                    }
                    Match.objects.update_or_create(date=match_date['date'])
                    stat_line = {
                        'match': get_object_or_404(Match, date=dt),
                        'date': dt,
                        'player': row._4,
                        'min': float(row._5.replace(',', '.')),
                        'made_2': row._6,
                        'attempts_2': row._8,
                        'made_3': row._10,
                        'made_3': row._10,
                        'attempts_3': row._12,
                        'made_ft': row._13,
                        'attempts_ft': row._14,
                        'reb_o': row._18,
                        'reb_d': row._19,
                        'assist': row._21,
                        'poa': row._22,
                        'pf': row._23,
                        'fd': row._24,
                        'steals': row._25,
                        'turnovers': row._26,
                        'blocks': row._27,
                    }
                    StatLine.objects.update_or_create(
                        date=stat_line['date'], player=stat_line['player'], defaults=stat_line)
            return redirect('matches')
    else:
        form = UploadForm()
    return render(request, 'upload.html', {'form': form})


tz = pytz.timezone('Atlantic/Reykjavik')


def match_list(request):
    matches = Match.objects.all()
    return render(request, 'match_list.html', {'matches': matches})


def match_details(request, pk):
    match = Match.objects.get(id=pk)
    queryset = StatLine.objects.filter(match_id=pk)
    return render(request, 'match_details.html', {'match': match, 'queryset': queryset})

templates/aggregation.html
{% extends 'base.html' %}
{% block title %} Aggregation Page {% endblock %}

{% block content %}

<br><br>
<h5>Summarized Stats for Players:</h5>
<p>Based on All Existing Database Entries</p>
<hr>
<br>
<table id="myTable" class="sortable table table-striped table-bordered text-center">
    <tr class="table-dark">
        <th>Player</th>
        <th>MIN</th>
        <th>2s</th>
        <th>A 2s</th>
        <th>% 2s</th>
        <th>3s</th>
        <th>A 3s</th>
        <th>% 3s</th>
        <th>FTs</th>
        <th>A FT</th>
        <th>% FT</th>
        <th>REB O</th>
        <th>REB D</th>
        <th>REB T</th>
        <th>A</th>
        <th>POA</th>
        <th>PF</th>
        <th>FD</th>
        <th>S</th>
        <th>TO</th>
        <th>B</th>
    </tr>
{% for player in players_agg %}
    <tr>
        <td>{{ player.player }}</td>
        <td>{{ player.sum_min }}</td>
        <td>{{ player.sum_made_2 }}</td>
        <td>{{ player.sum_attempts_2 }}</td>
        <td>{{ player.percentage_2 }}</td>
        <td>{{ player.sum_made_3 }}</td>
        <td>{{ player.sum_attempts_3 }}</td>
        <td>{{ player.percentage_3 }}</td>
        <td>{{ player.sum_made_ft }}</td>
        <td>{{ player.sum_attempts_ft }}</td>
        <td>{{ player.percentage_ft }}</td>
        <td>{{ player.sum_reb_o }}</td>
        <td>{{ player.sum_reb_d }}</td>
        <td>{{ player.sum_reb_t }}</td>
        <td>{{ player.sum_assist }}</td>
        <td>{{ player.sum_poa }}</td>
        <td>{{ player.sum_pf }}</td>
        <td>{{ player.sum_fd }}</td>
        <td>{{ player.sum_steals }}</td>
        <td>{{ player.sum_turnovers }}</td>
        <td>{{ player.sum_blocks }}</td>
    </tr>
{% endfor %}
</table>
<br>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {{ title }} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    
    <script src="{% static 'sort.js' %}"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Superteam Scrimmage Stats</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'aggregation' %}">Aggregation<span class="sr-only"></span></a>
              </li>
            </ul>                    
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'matches' %}">Matches<span class="sr-only"></span></a>
              </li>
            </ul>                    
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'upload' %}">New Upload<span class="sr-only"></span></a>
              </li>
            </ul>
          </div>
          {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'logout' %}">Logout<span class="sr-only"></span></a>
            </li>
          </ul>
          {% else %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only"></span></a>
            </li>
          </ul>
          {% endif %}
    </nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %} Alltime Stats {% endblock %}

{% block content %}


<br><br>
<h5>Alltime Stats:</h5>
<p>Full List of Database Entries Uploaded</p>
<hr>
<br>
<table id="myTable" class="sortable table table-striped table-bordered text-center">
    <tr class="table-dark">
        <th>#</th>
        <th>Date</th>
        <th>Player</th>
        <th>MIN</th>
        <th>2s</th>
        <th>A 2s</th>
        <th>% 2s</th>
        <th>3s</th>
        <th>A 3s</th>
        <th>% 3s</th>
        <th>FTs</th>
        <th>A FT</th>
        <th>% FT</th>
        <th>REB O</th>
        <th>REB D</th>
        <th>REB T</th>
        <th>A</th>
        <th>POA</th>
        <th>PF</th>
        <th>FD</th>
        <th>S</th>
        <th>TO</th>
        <th>B</th>
    </tr>

    {% for stat in statline_list %}
    <tr>
        <td>{{ stat.id }}</td>
        <td>{{ stat.date|date:'m-d-y #h' }}</td>
        <td>{{ stat.player }}</td>
        <td>{{ stat.min }}</td>
        <td>{{ stat.made_2 }}</td>
        <td>{{ stat.attempts_2 }}</td>
        <td>{{ stat.percentage_2 }}</td>
        <td>{{ stat.made_3 }}</td>
        <td>{{ stat.attempts_3 }}</td>
        <td>{{ stat.percentage_3 }}</td>
        <td>{{ stat.made_ft }}</td>
        <td>{{ stat.attempts_ft }}</td>
        <td>{{ stat.percentage_ft }}</td>
        <td>{{ stat.reb_o }}</td>
        <td>{{ stat.reb_d }}</td>
        <td>{{ stat.reb_t }}</td>
        <td>{{ stat.assist }}</td>
        <td>{{ stat.poa }}</td>
        <td>{{ stat.pf }}</td>
        <td>{{ stat.fd }}</td>
        <td>{{ stat.steals }}</td>
        <td>{{ stat.turnovers }}</td>
        <td>{{ stat.blocks }}</td>
    </tr>
    {% endfor %}  
</table>
<br>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/match_details.html
{% extends 'base.html' %}
{% block title %} Stats for: {{ match.date|date:'m-d-y #h' }}{% endblock %}

{% block content %} 

<br><br>
<h5>Stats for {{ match.date|date:'m-d-y #h' }} Match</h5>
<hr><br>
<table id="myTable" class="sortable table table-striped table-bordered text-center">
    <tr class="table-dark">
        <th>#</th>
        <th>Player</th>
        <th>MIN</th>
        <th>2s</th>
        <th>A 2s</th>
        <th>% 2s</th>
        <th>3s</th>
        <th>A 3s</th>
        <th>% 3s</th>
        <th>FTs</th>
        <th>A FT</th>
        <th>% FT</th>
        <th>REB O</th>
        <th>REB D</th>
        <th>REB T</th>
        <th>A</th>
        <th>POA</th>
        <th>PF</th>
        <th>FD</th>
        <th>S</th>
        <th>TO</th>
        <th>B</th>
    </tr>
    {% for stat in queryset %}
    <tr>
        <td>{{ stat.id }}</td>       
        <td>{{ stat.player }}</td>
        <td>{{ stat.min }}</td>
        <td>{{ stat.made_2 }}</td>
        <td>{{ stat.attempts_2 }}</td>
        <td>{{ stat.percentage_2 }}</td>
        <td>{{ stat.made_3 }}</td>
        <td>{{ stat.attempts_3 }}</td>
        <td>{{ stat.percentage_3 }}</td>
        <td>{{ stat.made_ft }}</td>
        <td>{{ stat.attempts_ft }}</td>
        <td>{{ stat.percentage_ft }}</td>
        <td>{{ stat.reb_o }}</td>
        <td>{{ stat.reb_d }}</td>
        <td>{{ stat.reb_t }}</td>
        <td>{{ stat.assist }}</td>
        <td>{{ stat.poa }}</td>
        <td>{{ stat.pf }}</td>
        <td>{{ stat.fd }}</td>
        <td>{{ stat.steals }}</td>
        <td>{{ stat.turnovers }}</td>
        <td>{{ stat.blocks }}</td>
    </tr>
    {% endfor %}

{% endblock %}

templates/match_list.html
{% extends 'base.html' %}
{% block title %} Latest Matches {% endblock %}

{% block content %}

    <br><br>
    <h5>Matches:</h5>
    <p>From Latest to Earliest</p>
    <hr><br>
    <ul>
        {% for match in matches %}
            <li><a href="{% url 'match' match.pk %}">{{ match.date|date:'m-d-y #h' }}</a></li>
        {% endfor %} 
    </ul>

    <br>
{% endblock %}

templates/stats.html
{% extends 'base.html' %}
{% block title %} All Uploaded Stats {% endblock %}

{% block content %}
<br><br>
<h5>Alltime Stats:</h5>
<hr>
<br>
<table id="myTable" class="table table-striped table-bordered text-center">
    <tr class="table-dark">
        <th onclick="sortTable(0)">#</th>
        <th onclick="sortTable(1)">Date</th>
        <th onclick="sortTable(2)">Player</th>
        <th onclick="sortTable(3)">MIN</th>
        <th onclick="sortTable(4)">2s</th>
        <th onclick="sortTable(5)">A 2s</th>
        <th onclick="sortTable(6)">3s</th>
        <th onclick="sortTable(7)">A 3s</th>
        <th onclick="sortTable(8)">FTs</th>
        <th onclick="sortTable(9)">A FT</th>
        <th onclick="sortTable(10)">REB O</th>
        <th onclick="sortTable(11)">REB D</th>
        <th onclick="sortTable(12)">A</th>
        <th onclick="sortTable(13)">POA</th>
        <th onclick="sortTable(14)">PF</th>
        <th onclick="sortTable(15)">FD</th>
        <th onclick="sortTable(16)">S</th>
        <th onclick="sortTable(17)">TO</th>
        <th onclick="sortTable(18)">B</th>
    </tr>
    {% for stat in statline_list %}
    <tr>
        <td>{{ stat.id }}</td>
        <td>{{ stat.date|date:'m/d/y-h' }}</td>
        <td>{{ stat.player }}</td>
        <td>{{ stat.min }}</td>
        <td>{{ stat.made_2 }}</td>
        <td>{{ stat.attempts_2 }}</td>
        <td>{{ stat.made_3 }}</td>
        <td>{{ stat.attempts_3 }}</td>
        <td>{{ stat.made_ft }}</td>
        <td>{{ stat.attempts_ft }}</td>
        <td>{{ stat.reb_o }}</td>
        <td>{{ stat.reb_d }}</td>
        <td>{{ stat.assist }}</td>
        <td>{{ stat.poa }}</td>
        <td>{{ stat.pf }}</td>
        <td>{{ stat.fd }}</td>
        <td>{{ stat.turnovers }}</td>
<!-- Why?? -->
        <td>{{ stat.blocks }}</td>
        <td>{{ stat.blocks }}</td>
    </tr>
    {% endfor %}  
</table>
<br>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("myTable");
  switching = true;
  //Set the sorting direction to ascending:
  dir = "asc"; 
  /*Make a loop that will continue until
  no switching has been done:*/
  while (switching) {
    //start by saying: no switching is done:
    switching = false;
    rows = table.rows;
    /*Loop through all table rows (except the
    first, which contains table headers):*/
    for (i = 1; i < (rows.length - 1); i++) {
      //start by saying there should be no switching:
      shouldSwitch = false;
      /*Get the two elements you want to compare,
      one from current row and one from the next:*/
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      /*check if the two rows should switch place,
      based on the direction, asc or desc:*/
      if (dir == "asc") {
        if (parseInt(x.innerHTML, 10) > parseInt(y.innerHTML, 10)) {
          //if so, mark as a switch and break the loop:
          shouldSwitch= true;
          break;
        }
      } else if (dir == "desc") {
        if (parseInt(x.innerHTML, 10) < parseInt(y.innerHTML, 10)) {
          //if so, mark as a switch and break the loop:
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
      switchcount ++;      
    } else {
      /*If no switching has been done AND the direction is "asc",
      set the direction to "desc" and run the while loop again.*/
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}
</script>
{% endblock %}

templates/upload.html
{% extends 'base.html' %}
{% block title %} Upload Page {% endblock %}

{% block content %}

    <br><br>
    <h5>Upload a new excel file:</h1>
    <hr>
    {% for msg in messages %}
        <div class="alert"> {{ msg }} </div>
    {% endfor %}
    <div class="w-50 p-3">
        <form method='POST' action="" enctype="multipart/form-data">
            {% csrf_token %} 
            {{ form.as_p }} 
            <br>
            <button class="btn btn-primary" value="Save">Submit</button>
        </form>
    </div>

{% endblock %}